---
openapi: 3.0.0
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
tags:
  - name: User
    description: Operations about user
paths:
  /registration:
    post:
      tags:
        - User
      summary: This endpoint is to register a new account.
      operationId: registration
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegistrationResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    RegistrationRequest:
      type: object
      properties:
        phone_number:
          type: string
        full_name:
          type: string
        password:
          type: string
    RegistrationResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/RegistrationResponseData"
        meta:
          $ref: "#/components/schemas/RegistrationResponseMeta"
    RegistrationResponseData:
      type: object
      properties:
        user_id:
          type: string
    RegistrationResponseMeta:
      type: object
    ErrorResponse:
      type: object
      properties:
        errors:
          $ref: "#/components/schemas/ErrorResponseData"
        meta:
          $ref: "#/components/schemas/RegistrationResponseMeta"
    ErrorResponseData:
      type: array
      items:
        properties:
          message:
            type: string
