---
openapi: 3.0.0
info:
  version: 1.0.0
  title: User Service
  license:
    name: MIT
servers:
  - url: http://localhost
tags:
  - name: User
    description: Operations about user
paths:
  /register:
    post:
      tags:
        - User
      summary: This endpoint is to register a new account.
      operationId: register
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        "200":
          description: A successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        phone_number:
          type: string
        full_name:
          type: string
        password:
          type: string
    RegisterResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/RegisterResponseData"
    RegisterResponseData:
      type: object
      properties:
        userID:
          type: integer
          format: uint64
          example: 20
    ErrorResponse:
      type: object
      nullable: true
      properties:
        message:
          type: string
          example: Phone number is below a minimum of 10 characters.
